use shopping_db;

select * from customer_behavior;

-- Q1. what is the total revenue generated by male vs female customers?
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer_behavior
GROUP BY gender;


-- Q2.which customers used a discount but still spent more than the average purchase amount ?
SELECT 
    customer_id, purchase_amount
FROM
    customer_behavior
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer_behavior);

-- Q3.Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    round(AVG(review_rating),2)AS avg_rating
FROM customer_behavior
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4.Compare the average Purchase Amount between Standard and Express Shipping
SELECT 
    shipping_type, AVG(purchase_amount) AS avg_purchase
FROM
    customer_behavior
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5. which Shipping type customer more use?
SELECT 
    shipping_type,
    COUNT(*) AS total_orders
FROM customer_behavior
GROUP BY shipping_type
ORDER BY total_orders DESC
LIMIT 3;

-- Q6.Do subscribed customers spend more?  compare average spend and total revenue between subscribers and non - subscribers
SELECT 
    subscription_status,
    count(customer_id) as total_customers,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status
order by total_revenue,avg_spend desc;

-- Q7. which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(100*sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_behavior
group by item_purchased
order by discount_rate desc
limit 5;

-- Q8.segement customers into new,returning , and loyal based on their total numbers of previous purchases,and show the count of each segment
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_behavior
)


select customer_segment,count(*) as 'Number of customers'
from customer_type
group by customer_segment;

-- Q9.what are the top 3 most purchased product within each category
WITH product_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer_behavior
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_purchases
FROM product_counts
WHERE rn <= 3
ORDER BY category, total_purchases DESC;

-- Q10.Are customers who are repeat buyers (more than 5 previous purrchases) also likely to subsribe?
select subscription_status,
count(customer_id) as reapeat_buyers
from customer_behavior
where previous_purchases > 5
group by subscription_status;

#Q11.what is the revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc;


